// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using FiveNine_Collective_Site.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiveNine_Collective_Site.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiveNine_Collective_Site.Data.CanvasItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth0Sub")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CanvasItems", (string)null);

                    b.HasDiscriminator<string>("Kind").HasValue("CanvasItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FiveNine_Collective_Site.Data.Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanvasItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Col")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("H")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("W")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CanvasItemId");

                    b.ToTable("Widgets");
                });

            modelBuilder.Entity("FiveNine_Collective_Site.Data.ProfileItem", b =>
                {
                    b.HasBaseType("FiveNine_Collective_Site.Data.CanvasItem");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasIndex("Auth0Sub")
                        .IsUnique()
                        .HasDatabaseName("IX_CanvasItems_ProfileAuth0Sub")
                        .HasFilter("\"Kind\" = 'profile'");

                    b.HasDiscriminator().HasValue("profile");
                });

            modelBuilder.Entity("FiveNine_Collective_Site.Data.ProjectItem", b =>
                {
                    b.HasBaseType("FiveNine_Collective_Site.Data.CanvasItem");

                    b.PrimitiveCollection<List<string>>("CollaboratorSubs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(560)
                        .HasColumnType("character varying(560)");

                    b.HasDiscriminator().HasValue("project");
                });

            modelBuilder.Entity("FiveNine_Collective_Site.Data.Widget", b =>
                {
                    b.HasOne("FiveNine_Collective_Site.Data.CanvasItem", "CanvasItem")
                        .WithMany("Widgets")
                        .HasForeignKey("CanvasItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanvasItem");
                });

            modelBuilder.Entity("FiveNine_Collective_Site.Data.CanvasItem", b =>
                {
                    b.Navigation("Widgets");
                });
#pragma warning restore 612, 618
        }
    }
}
